.TH mysqlman 1 "30 March 2014" "tailserver" ""
.SH NAME
tailserverman \- default man page for tailserver
.SH "DESCRIPTION"
This version is way too much of an alpha for a manpage. 
.SH "SEE ALSO"
Run "tailserver --help" to get what you need!
.SH BUGS
Obviously, there are no bugs at this stage of program maturity.
.\" end of man page
